### ISSUE TITLE
Backup retention setting does not persist

### ISSUE THREAD

**Issue by perf3ktion** [Pockity/tracker#3]
### Summary
When modifying the number of backups to retain on the local device, the setting does not persist and returns to default value of 5.

### Steps to reproduce

1. Click the settings icon in the top left
2. Select Data > Backups
3. Modify the value higher or lower than the default
4. Click ‘Settings’ to return to the Settings menu
5. Select Data > Backups
6. The number of daily backups will revert to the default (5).

### Device Details
The bug can be observed on both iPadOS and iOS.

### iPad
**Model:** iPad Air (Gen 5)
**Model #:** A2588
**iOS Version:** iPadOS 16.1.1 (20B101)
**App Version:** 2023.4.3 (200)

### iPhone
**Model:** iPhone 12 Pro
**Model #:** A2407
**iOS Version:** iOS 16.4.1 (20E252)
**App Version:** 2023.4.3 (200)

**Comment by dezinezync** [comment]
Fixed in v2023.4.4, released on 21st April, 2023
